### ISSUE TITLE
object queries fail

### ISSUE THREAD

**Issue by dpetran** [fluree/db#354]
Different values for ?o either return incorrect results or throws errors.

```
(def conn (test-utils/create-conn))
(def ledger @(fluree/create conn "query/everything" {:context {:ex "http://example.org/ns/"}}))
(def db @(fluree/stage
           (fluree/db ledger)
           {:graph [{:id          :ex/bob,
                     :type        :ex/User,
                     :schema/name "Bob"
                     :schema/age  22}]}))

;; returns wrong result
@(fluree/query db {:select ['?s '?p]
                   :where [['?s '?p 22]]})
;; => []

;; throws error
@(fluree/query db {:select ['?s '?p]
                   :where [['?s '?p "Bob"]]})
```

The error thrown on the second query:
```
ERROR f.db.query.exec.where - Error resolving flake range
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at fluree.db.flake$cmp_long.invokeStatic(flake.cljc:310)
	at fluree.db.flake$cmp_long.invoke(flake.cljc:309)
	at fluree.db.flake$cmp_subj.invokeStatic(flake.cljc:318)
	at fluree.db.flake$cmp_subj.invoke(flake.cljc:314)
	at fluree.db.flake$cmp_flakes_opst.invokeStatic(flake.cljc:402)
	at fluree.db.flake$cmp_flakes_opst.invoke(flake.cljc:400)
	at clojure.lang.AFunction.compare(AFunction.java:51)
	at clojure.data.avl$insert_BANG_.invokeStatic(avl.clj:797)
	at clojure.data.avl$insert_BANG_.invoke(avl.clj:791)
	at clojure.data.avl.AVLTransientMap.assoc(avl.clj:1606)
	at clojure.data.avl.AVLTransientSet.conj(avl.clj:1810)
	at clojure.core$conj_BANG_.invokeStatic(core.clj:3367)
	at clojure.core$conj_BANG_.invoke(core.clj:3359)
	at clojure.lang.ArraySeq.reduce(ArraySeq.java:119)
	at clojure.core$reduce.invokeStatic(core.clj:6885)
	at clojure.core$reduce.invoke(core.clj:6868)
	at clojure.data.avl$sorted_set_by.invokeStatic(avl.clj:1933)
	at clojure.data.avl$sorted_set_by.doInvoke(avl.clj:1928)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:662)
	at fluree.db.flake$sorted_set_by.invokeStatic(flake.cljc:526)
	at fluree.db.flake$sorted_set_by.doInvoke(flake.cljc:524)
	at clojure.lang.RestFn.invoke(RestFn.java:439)
	at fluree.db.query.range$resolve_flake_slices.invokeStatic(range.cljc:154)
	at fluree.db.query.range$resolve_flake_slices.invoke(range.cljc:146)
	at fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708$fn__29710.invoke(where.cljc:51)
	at fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708.invoke(where.cljc:32)
	at clojure.core.async.impl.runtime$run_state_machine.invokeStatic(runtime.clj:62)
	at clojure.core.async.impl.runtime$run_state_machine.invoke(runtime.clj:61)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invokeStatic(runtime.clj:66)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invoke(runtime.clj:64)
	at fluree.db.query.exec.where$resolve_flake_range$fn__29663.invoke(where.cljc:32)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__1977$fn__1978.invoke(concurrent.clj:29)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:829)
ERROR fluree.db.json-ld.api - #error {
 :cause "class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')"
 :via
 [{:type java.lang.ClassCastException
   :message "class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')"
   :at [fluree.db.flake$cmp_long invokeStatic "flake.cljc" 310]}]
 :trace
 [[fluree.db.flake$cmp_long invokeStatic "flake.cljc" 310]
  [fluree.db.flake$cmp_long invoke "flake.cljc" 309]
  [fluree.db.flake$cmp_subj invokeStatic "flake.cljc" 318]
  [fluree.db.flake$cmp_subj invoke "flake.cljc" 314]
  [fluree.db.flake$cmp_flakes_opst invokeStatic "flake.cljc" 402]
  [fluree.db.flake$cmp_flakes_opst invoke "flake.cljc" 400]
  [clojure.lang.AFunction compare "AFunction.java" 51]
  [clojure.data.avl$insert_BANG_ invokeStatic "avl.clj" 797]
  [clojure.data.avl$insert_BANG_ invoke "avl.clj" 791]
  [clojure.data.avl.AVLTransientMap assoc "avl.clj" 1606]
  [clojure.data.avl.AVLTransientSet conj "avl.clj" 1810]
  [clojure.core$conj_BANG_ invokeStatic "core.clj" 3367]
  [clojure.core$conj_BANG_ invoke "core.clj" 3359]
  [clojure.lang.ArraySeq reduce "ArraySeq.java" 119]
  [clojure.core$reduce invokeStatic "core.clj" 6885]
  [clojure.core$reduce invoke "core.clj" 6868]
  [clojure.data.avl$sorted_set_by invokeStatic "avl.clj" 1933]
  [clojure.data.avl$sorted_set_by doInvoke "avl.clj" 1928]
  [clojure.lang.RestFn applyTo "RestFn.java" 139]
  [clojure.core$apply invokeStatic "core.clj" 669]
  [clojure.core$apply invoke "core.clj" 662]
  [fluree.db.flake$sorted_set_by invokeStatic "flake.cljc" 526]
  [fluree.db.flake$sorted_set_by doInvoke "flake.cljc" 524]
  [clojure.lang.RestFn invoke "RestFn.java" 439]
  [fluree.db.query.range$resolve_flake_slices invokeStatic "range.cljc" 154]
  [fluree.db.query.range$resolve_flake_slices invoke "range.cljc" 146]
  [fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708$fn__29710 invoke "where.cljc" 51]
  [fluree.db.query.exec.where$resolve_flake_range$fn__29663$state_machine__7578__auto____29708 invoke "where.cljc" 32]
  [clojure.core.async.impl.runtime$run_state_machine invokeStatic "runtime.clj" 62]
  [clojure.core.async.impl.runtime$run_state_machine invoke "runtime.clj" 61]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invokeStatic "runtime.clj" 66]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invoke "runtime.clj" 64]
  [fluree.db.query.exec.where$resolve_flake_range$fn__29663 invoke "where.cljc" 32]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 628]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__1977$fn__1978 invoke "concurrent.clj" 29]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 829]]}
```

**Comment by zonotope** [comment]
This is an artifact of only storing references in the opst index. We use the opst index for (reverse) relationship lookups between subjects, so [only reference objects are added to the opst index](https://github.com/fluree/db/blob/main/src/fluree/db/json_ld/transact.cljc#L324) after a transaction. This way, we can use the [subject comparator as the primary comparator for the opst index](https://github.com/fluree/db/blob/main/src/fluree/db/flake.cljc#L402), which, because it's only comparing integers at it's core, is much, _much_ faster than the [object comparator](https://github.com/fluree/db/blob/main/src/fluree/db/flake.cljc#L336-L364) which has to use extra logic to compare arbitrary types. 

I'm not sure what to do about this. Granted, it would be nice if a query like this worked, but I can't think of a real use case where someone wanted "give me every subject and predicate who's value is 22". That could give an age, shoe size, or any number of different values. "22" without any other information is meaningless. If the user supplies the predicate in the query, then everything works because we'd use the post index for the lookup. 

We cannot store arbitrary objects in the opst index because that would make it unusable for the only valid use case we've identified for it. We _could_ create a new index to store all the objects in the database, but that's a pretty heavy lift to support a query type of questionable value. 

I say we leave this as is and revisit if an external user identifies a use case for looking up flakes by an arbitrary object (and *only* that object) that they can't accomplish any other way.

**Comment by bplatz** [comment]
If easy enough to detect, we could throw an exception indicating this query pattern is not supported... which would be a more desirable short-term solution

I don't think worthy of a special index, but an unusual solution for an unusual query could be doing a full index scan with a filtering function. For large enough databases, eventually they'd run out of fuel and it would terminate.

**Comment by zonotope** [comment]
> If easy enough to detect, we could throw an exception indicating this query pattern is not supported... which would be a more desirable short-term solution
> 
> I don't think worthy of a special index, but an unusual solution for an unusual query could be doing a full index scan with a filtering function. For large enough databases, eventually they'd run out of fuel and it would terminate.

The case when the passed in object is not an integer is easy to detect, and we could throw an exception (or do a full scan of another index) in that case, but I can't think of a way to deal with disambiguating a random integer from a subject id without requiring the user to encode the two cases differently in the query.

**Comment by dpetran** [comment]
I think we should not allow users to supply subject ids in analytical queries. If they want to query with internal index-implementation-specific machinery they should have to use the index range and slice api.

At the philosophical level, accepting subject ids is antithetical to open rdf data - it silos it away and makes it machine/ledger specific.

If that simplifies this that would be nice.
