### ISSUE TITLE
NullPointerException at file conn load

### ISSUE THREAD

**Issue by dpetran** [fluree/db#567]
Seeing the error below while trying to load a file conn.

One thing that catches my eye is the "///" substring of the head file `file:///369435906932762/main/head`. I suspect we are not properly encoding the commit address in the head file.

```
Exception in thread "async-dispatch-61" java.lang.NullPointerException: Cannot invoke "Object.toString()" because "s" is null
	at clojure.string$starts_with_QMARK_.invokeStatic(string.clj:365)
	at clojure.string$starts_with_QMARK_.invoke(string.clj:361)
	at fluree.db.conn.file$file_address.invokeStatic(file.cljc:30)
	at fluree.db.conn.file$file_address.invoke(file.cljc:27)
	at fluree.db.conn.file.FileConnection$fn__53589$state_machine__16910__auto____53618$fn__53620.invoke(file.cljc:227)
	at fluree.db.conn.file.FileConnection$fn__53589$state_machine__16910__auto____53618.invoke(file.cljc:227)
	at clojure.core.async.impl.runtime$run_state_machine.invokeStatic(runtime.clj:62)
13:16:28.853 [async-dispatch-62] ERROR fluree.db.json-ld.api - #error {
 :cause "Unable to load. No commit exists for: fluree:[file://fluree-jld/369435906932762/main/head](file:///369435906932762/main/head)"
 :data {:status 400, :error :db/invalid-commit-address}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "Unable to load. No commit exists for: fluree:[file://fluree-jld/369435906932762/main/head](file:///369435906932762/main/head)"
   :data {:status 400, :error :db/invalid-commit-address}
   :at [fluree.db.ledger.json_ld$load$fn__61838$state_machine__16910__auto____61843$fn__61846 invoke "json_ld.cljc" 219]}]
 :trace
 [[fluree.db.ledger.json_ld$load$fn__61838$state_machine__16910__auto____61843$fn__61846 invoke "json_ld.cljc" 219]
  [fluree.db.ledger.json_ld$load$fn__61838$state_machine__16910__auto____61843 invoke "json_ld.cljc" 216]
  [clojure.core.async.impl.runtime$run_state_machine invokeStatic "runtime.clj" 62]
  [clojure.core.async.impl.runtime$run_state_machine invoke "runtime.clj" 61]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invokeStatic "runtime.clj" 66]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invoke "runtime.clj" 64]
  [clojure.core.async.impl.runtime$take_BANG_$fn__11046 invoke "runtime.clj" 75]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__10905 invoke "channels.clj" 269]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1136]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 635]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__10709$fn__10710 invoke "concurrent.clj" 29]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.lang.Thread run "Thread.java" 833]]}
	at clojure.core.async.impl.runtime$run_state_machine.invoke(runtime.clj:61)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invokeStatic(runtime.clj:66)
	at clojure.core.async.impl.runtime$run_state_machine_wrapped.invoke(runtime.clj:64)
	at fluree.db.conn.file.FileConnection$fn__53589.invoke(file.cljc:227)
2023-08-30T18:10:59.356974Z :post "/fluree/multi-query" => Error in ledger handler
clojure.lang.ExceptionInfo: Error in ledger handler {:response {:status 400, :body {:error :db/invalid-commit-address, :message "Unable to load. No commit exists for: fluree:[file://fluree-jld/369435906932761/main/head](file:///369435906932761/main/head)"}}}
	at fluree.http_api.handlers.shared$error_catching_handler$fn__62072.invoke(shared.clj:19)
	at clojure.lang.Var.invoke(Var.java:384)
	at reitit.ring.middleware.exception$wrap$fn__67334$fn__67335.invoke(exception.clj:49)
	at reitit.ring.coercion$fn__67269$fn__67271$fn__67272.invoke(coercion.cljc:40)
	at reitit.ring.coercion$fn__67279$fn__67281$fn__67282.invoke(coercion.cljc:64)
	at reitit.ring.coercion$fn__67292$fn__67294$fn__67295.invoke(coercion.cljc:80)
	at fluree.http_api.components.http$unwrap_credential$fn__67685.invoke(http.clj:219)
	at fluree.http_api.components.http$wrap_set_fuel_header$fn__67690.invoke(http.clj:224)
	at fluree.http_api.components.http$wrap_assoc_conn$fn__67680.invoke(http.clj:187)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.cljc:178)
	at ring.middleware.cors$handle_cors.invoke(cors.cljc:167)
	at ring.middleware.cors$wrap_cors$fn__67662.invoke(cors.cljc:205)
	at reitit.ring.middleware.exception$wrap$fn__67334$fn__67335.invoke(exception.clj:49)
	at muuntaja.middleware$wrap_format_request$fn__67398.invoke(middleware.clj:114)
	at muuntaja.middleware$wrap_format_response$fn__67402.invoke(middleware.clj:132)
	at muuntaja.middleware$wrap_format_negotiate$fn__67395.invoke(middleware.clj:96)
	at reitit.ring$ring_handler$fn__67125.invoke(ring.cljc:328)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at ring.adapter.jetty9.handlers.sync$_doHandle.invokeStatic(sync.clj:30)
	at ring.adapter.jetty9.handlers.sync$_doHandle.invoke(sync.clj:21)
	at ring.adapter.jetty9.handlers.SyncProxyHandler.doHandle(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at ring.adapter.jetty9.handlers.SyncProxyHandler.doScope(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:833)
#error {
 :cause Unable to load. No commit exists for: fluree:[file://fluree-jld/369435906932762/main/head](file:///369435906932762/main/head)
 :data {:status 400, :error :db/invalid-commit-address}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message Unable to load. No commit exists for: fluree:[file://fluree-jld/369435906932762/main/head](file:///369435906932762/main/head)
   :data {:status 400, :error :db/invalid-commit-address}
   :at [fluree.db.ledger.json_ld$load$fn__61838$state_machine__16910__auto____61843$fn__61846 invoke json_ld.cljc 219]}]
 :trace
 [[fluree.db.ledger.json_ld$load$fn__61838$state_machine__16910__auto____61843$fn__61846 invoke json_ld.cljc 219]
  [fluree.db.ledger.json_ld$load$fn__61838$state_machine__16910__auto____61843 invoke json_ld.cljc 216]
  [clojure.core.async.impl.runtime$run_state_machine invokeStatic runtime.clj 62]
  [clojure.cor	at clojure.lang.AFn.run(AFn.java:22)
e.async.impl.runtime$run_state_machine invoke runtime.clj 61]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invokeStatic runtime.clj 66]
  [clojure.core.async.impl.runtime$run_state_machine_wrapped invoke runtime.clj 64]
  [clojure.core.async.impl.runtime$take_BANG_$fn__11046 invoke runtime.clj 75]
  [clojure.core.async.impl.channels.ManyToManyChannel$fn__10905 invoke channels.clj 269]
  [clojure.lang.AFn run AFn.java 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1136]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 635]
  [clojure.core.async.impl.concurrent$counted_thread_factory$reify__10709$fn__10710 invoke concurrent.clj 29]
  [clojure.lang.AFn run AFn.java 22]
  [java.lang.Thread run Thread.java 833]]}
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__10709$fn__10710.invoke(concurrent.clj:29)
13:16:30.141 [async-dispatch-58] DEBUG fluree.db.json-ld.api - Looking up address for ledger alias "fluree-jld/369435906932762"
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by JaceRockman** [comment]
This error seems to have been fixed by other development.
