### ISSUE TITLE
Indexing stopped errors

### ISSUE THREAD

**Issue by chrisdostert** [fluree/db#725]
When using the latest fluree/server docker image, I constantly see indexing errors when transacting, which result in subsequent queries not returning correct results. I have not been able to specifically pinpoint if anything in particular causes it; it seems to happen pretty regularly.

Of note,I can't replicate this erroneous behavior when using nexus, only when using the docker image. 

Error messages in the logs seem to be the following:

```sh
06:26:30.862 [async-dispatch-3] ERROR fluree.db.indexer.default - Error encountered creating index for db:  #FlureeJsonLdDb {:method nil, :alias "platform", :t -65, :stats {:flakes 1238, :size 295042, :indexed 47}, :policy {"https://ns.flur.ee/ledger#view" {:root? true}, "https://ns.flur.ee/ledger#modify" {:root? true}}} .  Indexing stopped.
clojure.lang.ExceptionInfo: Unable to create new DB version on ledger, latest 't' value is: -66 however new db t value is: -65.
        at fluree.db.json_ld.branch$update_db.invokeStatic(branch.cljc:67)
        at fluree.db.json_ld.branch$update_db.invoke(branch.cljc:57)
        at fluree.db.json_ld.branch$update_commit.invokeStatic(branch.cljc:107)
        at fluree.db.json_ld.branch$update_commit.invoke(branch.cljc:79)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$update_in$up__6922.invoke(core.clj:6220)
        at clojure.core$update_in$up__6922.invoke(core.clj:6219)
        at clojure.core$update_in.invokeStatic(core.clj:6221)
        at clojure.core$update_in.doInvoke(core.clj:6207)
        at clojure.lang.RestFn.applyTo(RestFn.java:146)
        at clojure.lang.Atom.swap(Atom.java:79)
        at clojure.core$swap_BANG_.invokeStatic(core.clj:2372)
        at clojure.core$swap_BANG_.doInvoke(core.clj:2362)
        at clojure.lang.RestFn.invoke(RestFn.java:529)
        at fluree.db.ledger.json_ld$commit_update.invokeStatic(json_ld.cljc:69)
        at fluree.db.ledger.json_ld$commit_update.invoke(json_ld.cljc:57)
        at fluree.db.ledger.json_ld.JsonLDLedger._commit_update(json_ld.cljc:178)
        at fluree.db.json_ld.commit$do_commit_PLUS_push$fn__54899$state_machine__14611__auto____54922$fn__54925.invoke(commit.cljc:307)
        at fluree.db.json_ld.commit$do_commit_PLUS_push$fn__54899$state_machine__14611__auto____54922.invoke(commit.cljc:289)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:971)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:976)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:974)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__14629.invoke(ioc_macros.clj:985)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__9672$fn__9673.invoke(channels.clj:100)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__9575$fn__9576.invoke(concurrent.clj:29)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by chrisdostert** [comment]
Not seeing this in latest version, will close out.

**Comment by bplatz** [comment]
Thanks @chrisdostert !
