### ISSUE TITLE
Bad `#uuid` json values found in indexes

### ISSUE THREAD

**Issue by alan-icebreaker** [fluree/db#914]
Im finding some logs in my server lately along these lines (apologies for the verbose dump here), the json outlined here has been truncated to isolate the bad shape...

at fluree.server16:07:43.452 [async-dispatch-1325] ERROR fluree.db.util.json - "Exception JSON-parsing: 

{
  "children": [
    {
      "first": [
        [103, "user-name-a3737326"],
        [102, "id"],
        "user-name-a3737326",
        [2, "string"],
        88,
        true,
        null
      ],
      "id": #uuid "e6e71f19-04a2-419d-b3be-e54c3f6b055a",  <-- This is the line that is causing the error
      "leaf": true,
      "leftmost?": false,
      "rhs": [
        [103, "foo-bar-a802121"],
        [102, "children"],
        "",
        [2, "string"],
        1274,
        true,
        null
      ],
      "size": 1908224
    }
  ]
}

    at cheshire.parse$parseSTAR.invoke(parse.clj:63)
    at cheshire.parse$parseSTAR.invokeStatic(parse.clj:66)
    at cheshire.parse$parseSTAR.invoke(parse.clj:63)
    at cheshire.parse$parseSTAR.invokeStatic(parse.clj:65)
    at cheshire.parse$parseSTAR.invoke(parse.clj:63)
    at cheshire.parse$parse.invokeStatic(parse.clj:100)
    at cheshire.parse$parse.invoke(parse.clj:88)
    at cheshire.core$parsestring.invokeStatic(core.clj:208)
    at cheshire.core$parse_string.invoke(core.clj:194)
    at cheshire.core$parse_string.invokeStatic(core.clj:205)
    at cheshire.core$parse_string.invoke(core.clj:194)
    at fluree.db.util.json$parse.invokeStatic(json.cljc:70)
    at fluree.db.util.json$parse.invoke(json.cljc:54)
    at fluree.db.storage.file.FileStore$fn46569$state_machine5947auto__46588$fn46591.invoke(file.cljc:39)
    at fluree.db.storage.file.FileStore$fn46569$state_machine5947auto____46588.invoke(file.cljc:36)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:972)
    at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:971)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:976)
    at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:974)
    at clojure.core.async.impl.ioc_macros$take_BANG$fn5965.invoke(ioc_macros.clj:985)
    at clojure.core.async.impl.channels.ManyToManyChannel$fn784$fn785.invoke(channels.clj:100)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at clojure.core.async.impl.concurrent$counted_thread_factory$reify687$fn__688.invoke(concurrent.clj:29)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.base/java.lang.Thread.run(Unknown Source)
16:07:43.452 [async-dispatch-1333] ERROR fluree.db.flake.index - Error resolving index node: {:id "fluree:ee.flur/main:file://icebreaker/userdata/index/spot/d230fb3e34c10b95fffa8236e7f6da7fb90c21c1a544c5d5bfb077df30bc0888.json", :ledger-alias "icebreaker/userdata"}
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('#' (code 35)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: REDACTED (StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION disabled); line: 1, column: 29323]
    at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2643)
...
...

**Comment by dpetran** [comment]
Could you share the un-truncated version of the json?

**Comment by dpetran** [comment]
And can you share what version you are using when you experience this error?

**Comment by alan-icebreaker** [comment]
I'm running the last docker build for `fluree/server`...

https://hub.docker.com/layers/fluree/server/60829de035c4996369f7dbe0766b80db0e743a8b/images/sha256-45379892326dfa912fd39b3b6a38eb51bea0ead743f3565d316632f0410d69c1?context=explore

**Comment by alan-icebreaker** [comment]
These are the tx's I found for this subject...

./78bd2ab817adbea8c356a575619aa1cb9fe959c19a862e5ad333810aaa096d1f.json:{"@context":{"f":"https://ns.flur.ee/ledger#","fc":"https://lod.icebreaker.xyz/schemas/fc/1.0/","icbk":"https://lod.icebreaker.xyz/schemas/icbk/1.0/"},"delete":[{"?p":"?o","@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"}],"insert":[{"@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326","@type":"icbk:SocialContact","StructConstructor":null,"icbk:addresses":[""],"icbk:bio":"🧑‍💻 Building....","icbk:emails":[""],"icbk:fullName":"Kevin Coleman","icbk:id":"https://linkedin.com/in/kevin-coleman-a3737326","icbk:instantMessageHandles":[""],"icbk:notes":[""],"icbk:pfpUrl":"https://media.licdn.com/dms/image/v2/C4D03AQFHBXCanAFBgg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517365517714?e=1733961600&v=beta&t=kRNMcPEZAJa6OZM3Yrgc7e5lJlvQxIGnjokF9lSx4Aw","icbk:phoneNumbers":[""],"icbk:sites":[""],"icbk:socialPath":"https://linkedin.com/in/kevin-coleman-a3737326","icbk:socialPaths":["https://linkedin.com/in/kevin-coleman-a3737326"],"icbk:source":"linkedin","skills":[""]},{"@id":"icbk:SocialContactConnection_clwhz3hjr00chlrfgw81pfvda_https://linkedin.com/in/kevin-coleman-a3737326","@type":"icbk:SocialContactConnection","icbk:socialContact":{"@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"},"icbk:user":{"@id":"icbk:User_clwhz3hjr00chlrfgw81pfvda"}}],"ledger":"icebreaker/userdata","where":[{"?p":"?o","@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"}]}

./fe69c3316b5ad7dbbdd96411e182ca5bdc63246efff08699bdbe5172ced0eb4d.json:{"@context":{"f":"https://ns.flur.ee/ledger#","fc":"https://lod.icebreaker.xyz/schemas/fc/1.0/","icbk":"https://lod.icebreaker.xyz/schemas/icbk/1.0/"},"delete":[{"?p":"?o","@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"}],"insert":[{"@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326","@type":"icbk:SocialContact","StructConstructor":null,"icbk:bio":"🧑‍💻 Building....","icbk:fullName":"Kevin Coleman","icbk:id":"https://linkedin.com/in/kevin-coleman-a3737326","icbk:pfpUrl":"https://media.licdn.com/dms/image/v2/C4D03AQFHBXCanAFBgg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517365517714?e=1734566400&v=beta&t=qHNCmTLwjYed04_CW5H-7G8B7HMlBdhzIRL6-e3hMmM","icbk:socialPath":"linkedin/kevin-coleman-a3737326","icbk:socialPaths":["linkedin/kevin-coleman-a3737326"],"icbk:source":"linkedin"},{"@id":"icbk:SocialContactConnection_clwhz3hjr00chlrfgw81pfvda_https://linkedin.com/in/kevin-coleman-a3737326","@type":"icbk:SocialContactConnection","icbk:socialContact":{"@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"},"icbk:user":{"@id":"icbk:User_clwhz3hjr00chlrfgw81pfvda"}}],"ledger":"icebreaker/userdata","where":[{"?p":"?o","@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"}]}

./dbef9cae9f01958b6985d63936e21463094d715314b1e05d08e1f918322c1f6f.json:{"@context":{"f":"https://ns.flur.ee/ledger#","fc":"https://lod.icebreaker.xyz/schemas/fc/1.0/","icbk":"https://lod.icebreaker.xyz/schemas/icbk/1.0/"},"delete":[{"?p":"?o","@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"}],"insert":[{"@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326","@type":"icbk:SocialContact","StructConstructor":null,"icbk:bio":"🧑‍💻 Building....","icbk:fullName":"Kevin Coleman","icbk:id":"https://linkedin.com/in/kevin-coleman-a3737326","icbk:pfpUrl":"https://media.licdn.com/dms/image/v2/C4D03AQFHBXCanAFBgg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1517365517714?e=1734566400&v=beta&t=qHNCmTLwjYed04_CW5H-7G8B7HMlBdhzIRL6-e3hMmM","icbk:socialPath":"kevin-coleman-a3737326","icbk:socialPaths":["kevin-coleman-a3737326"],"icbk:source":"linkedin"},{"@id":"icbk:SocialContactConnection_clwhz3hjr00chlrfgw81pfvda_https://linkedin.com/in/kevin-coleman-a3737326","@type":"icbk:SocialContactConnection","icbk:socialContact":{"@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"},"icbk:user":{"@id":"icbk:User_clwhz3hjr00chlrfgw81pfvda"}}],"ledger":"icebreaker/userdata","where":[{"?p":"?o","@id":"icbk:SocialContact_https://linkedin.com/in/kevin-coleman-a3737326"}]}

**Comment by bplatz** [comment]
Closed, old version
